export const REQUEST_POST_MEDIA = 'REQUEST_POST_MEDIA';
export const REQUEST_POST_MEDIA_ERROR = 'REQUEST_POST_MEDIA_ERROR';
export const UPDATE_POST_MEDIA = 'UPDATE_POST_MEDIA';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_POSTS_ERROR = 'REQUEST_POSTS_ERROR';
export const UPDATE_POSTS = 'UPDATE_POSTS';
